---
openapi: "3.0.3"
info:
  title: "UAM-EVENT"
  description: "UAM event"
  version: "2026-W17"
servers:
- url: "https"
- url: "http"
paths: {}
components:
  schemas:
    DomainEventType:
      type: "string"
      enum:
      - "USER_CREATED"
      - "USER_UPDATED"
      - "USER_DELETED"
    UserCreatedEventDTO:
      type: "object"
      properties:
        userId:
          type: "string"
          format: "uuid"
          description: "Keycloak user id"
        lastname:
          type: "string"
        firstname:
          type: "string"
        email:
          type: "string"
        phoneNumber:
          $ref: "#/components/schemas/PhoneNumberDTO"
        createdAt:
          type: "string"
          format: "date-time"
          description: "specify the user's creation date"
    UserUpdatedEventDTO:
      type: "object"
      properties:
        userId:
          type: "string"
          format: "uuid"
          description: "Keycloak user id"
        lastname:
          type: "string"
        firstname:
          type: "string"
        email:
          type: "string"
        phoneNumber:
          $ref: "#/components/schemas/PhoneNumberDTO"
        updatedAt:
          type: "string"
          format: "date-time"
    UserDeletedEventDTO:
      type: "object"
      properties:
        userId:
          type: "string"
          format: "uuid"
          description: "Keycloak user id"
        deletedAt:
          type: "string"
          format: "date-time"
    PhoneNumberDTO:
      type: "object"
      properties:
        countryCode:
          type: "string"
          description: "the international code for the country"
          example: "237 for Cameroon"
        number:
          type: "string"
          description: "the phone number"
          example: "653492410"
