---
openapi: "3.0.3"
info:
  title: "SERVICE-PROVIDER-EVENT"
  description: "Service provider domain event"
  version: "2026-W17"
servers:
- url: "https"
- url: "http"
paths: {}
components:
  schemas:
    DomainEventType:
      type: "string"
      enum:
      - "SERVICE_REQUEST_ACCEPTED"
    ServiceRequestAcceptedEventDTO:
      type: "object"
      required:
      - "id"
      - "userId"
      - "serviceTypeId"
      - "serviceProviderId"
      - "status"
      - "createdAt"
      properties:
        id:
          type: "string"
          format: "uuid"
        userId:
          type: "string"
          format: "uuid"
        serviceTypeId:
          type: "string"
          format: "uuid"
        serviceProviderId:
          type: "string"
          format: "uuid"
        title:
          type: "string"
        description:
          type: "string"
        acceptedAt:
          type: "string"
          format: "date-time"
        createdAt:
          type: "string"
          format: "date-time"
        status:
          $ref: "#/components/schemas/ServiceRequestStatus"
    ServiceRequestStatus:
      type: "string"
      enum:
      - "PENDING"
      - "ACCEPTED"
      - "REJECTED"
      - "CANCELLED"
